// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgkkdggjbbvbrcbvthjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpna2tkZ2dqYmJ2YnJjYnZ0aGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjY3NjksImV4cCI6MjA2OTY0Mjc2OX0.A1zWX9XIBgAY-rv2oBdQ8-SaTrUCs7w9d2t1XT_UweA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});